### ISSUE TITLE
Additional licences

### ISSUE THREAD

**Issue by madAle** [nning/david#2]
@nning is it possible to add additional licences to the project (e.g. MIT) ?

**Comment by nning** [comment]
How does the GPL not meet your needs? If there is a concrete commercial project that couldn't use david with a viral license, I consider relicensing to MIT.

**Comment by madAle** [comment]
I'm considering using david for a commercial software we'll release in the next months and gpl is not the best licence for such a project :)

**Comment by nning** [comment]
Ok, MIT it is! I changed the license and released version 0.4.4. Feel free to send pull requests for david and a pointer to the software project after the release!

**Comment by madAle** [comment]
Thank you! 
I'll let you know when we'll release!

**Comment by nning** [comment]
@madAle Did you decide to use David?

**Comment by madAle** [comment]
Hi @nning,
we're still working on the software that due to various problems hasn't yet been released :disappointed:
